#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

